homepage:
 path:     /homepage
 defaults:
  _controller: UserBundle:User:home

user:
    path:     /user
    defaults:
     _controller: UserBundle:User:user
user_add:
    path:     /user_add
    defaults:
     _controller: UserBundle:User:user_add
connect:
    path:     /connexion/{user}
    defaults:
     _controller: UserBundle:User:connect
homeUser:
    path:     /
    defaults:
     _controller: UserBundle:User:home
user_display_all:
    path:     /user_display_all
    defaults:
     _controller: UserBundle:User:user_display_all
