annonce_homepage:
    path:     /annonce
    defaults: { _controller: annonceBundle:Default:index }
begin:
    path:     /begin
    controller: annonceBundle:Annonce:begin
annonce_list:
    path:     /annone_list
    controller: annonceBundle:Annonce:annonce_list
annonce_add:
 path: /annonce_add
 controller: annonceBundle:Annonce:annonce_add
test:
  path: /test
  defaults:
    _controller: FrameworkBundle:Template:template
    template: '..\..\..\src\annonceBundle\Resources\views/Static/page_test.html.twig'

