<?php

namespace User\userBundle\Repository\User;

/**
 * userBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userBundleRepository extends \Doctrine\ORM\EntityRepository
{
}
